---
# tasks file for pass

- name: pass | install pass requirements
  become: yes
  package:
    name: "{{ pass_packages }}"
    state: present
  register: pass_install_pass
  until: pass_install_pass is succeeded
  retries: 3

- name: pass | Set pass temporary location
  set_fact: pass_src_home={{ ansible_env.HOME }}/src/pass

#- name: debug home value
#  debug:
#    var: pass_src_home
  
#- name: Create directory
#  file:
#    path: "{{ pass_src_home }}"
#    state: directory

- name: "pass | Download pass version {{ pass_version }}"
  get_url:
    url: "{{ pass_url }}"
    dest: /tmp
  register: pass_source_download

- name: pass | Extract sources
  unarchive:
    src: /tmp/password-store-{{ pass_version }}.tar.xz
    dest: /tmp
    copy: no
  when: pass_source_download.changed

- name: pass | Run make install
  become: yes
  command: make install
  args:
    chdir: /tmp/password-store-{{ pass_version }}
    creates: /usr/bin/pass
